#!/bin/python

import math
import os
import random
import re
import sys

# Complete the hourglassSum function below.
def hourglassSum(arr):
    gls = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    k= 0
    p = 0
    f = 0
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            m=j;
            n = j
            if j <= len(arr[i])-3 and i <= len(arr)-3:
                for r in range(3):
                    gls[k] += arr[i][n]
                    n+=1
                k+=1

            if i > 0 and i <= len(arr)-2 and j >0 and j<= len(arr[i])-2:
                gls[p] += arr[i][j]
                p+=1

            if i > 1 and i <= len(arr)-1 and j <= len(arr[i])-3:
                for r in range(3):
                    gls[f] += arr[i][m]
                    m+=1
                f+=1
    return max(gls)
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr = []

    for _ in xrange(6):
        arr.append(map(int, raw_input().rstrip().split()))

    result = hourglassSum(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
