#!/bin/python

import math
import os
import random
import re
import sys

# Complete the hourglassSum function below.
def hourglassSum(arr):
    sum = None
    if(len(arr)>=3):
        for i in range(len(arr)-2):
            for j in range(len(arr[i])-2):
                sumNew =  (arr[i][j]+ arr[i][j+1]+arr[i][j+2])+ (arr[i+1][j+1])+ (arr[i+2][j]+arr[i+2][j+1]+arr[i+2][j+2])
                if sum is None:
                    sum = sumNew
                if(sumNew > sum):
                    sum = sumNew   
        return sum
    else:
        return 0
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr = []

    for _ in xrange(6):
        arr.append(map(int, raw_input().rstrip().split()))

    result = hourglassSum(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
